//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace XmlDiffXmlFileFinder.CrmOnDemandFieldManagementService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FieldManagementService", Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementService : Microsoft.Web.Services3.WebServicesClientProtocol
    {        
        private System.Threading.SendOrPostCallback FieldManagementReadAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback FieldManagementReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback FieldManagementUpsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback FieldManagementCreateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FieldManagementService() {
            this.Url = global::XmlDiffXmlFileFinder.Properties.Settings.Default.XmlDiffXmlFileFinder_CrmOnDemandFieldManagementService_FieldManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FieldManagementReadAllCompletedEventHandler FieldManagementReadAllCompleted;
        
        /// <remarks/>
        public event FieldManagementReadCompletedEventHandler FieldManagementReadCompleted;
        
        /// <remarks/>
        public event FieldManagementUpsertCompletedEventHandler FieldManagementUpsertCompleted;
        
        /// <remarks/>
        public event FieldManagementCreateCompletedEventHandler FieldManagementCreateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementReadAll", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FieldManagementReadAll_Output", Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
        public FieldManagementReadAll_Output FieldManagementReadAll([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")] FieldManagementReadAll_Input FieldManagementReadAll_Input) {
            object[] results = this.Invoke("FieldManagementReadAll", new object[] {
                        FieldManagementReadAll_Input});
            return ((FieldManagementReadAll_Output)(results[0]));
        }
        
        /// <remarks/>
        public void FieldManagementReadAllAsync(FieldManagementReadAll_Input FieldManagementReadAll_Input) {
            this.FieldManagementReadAllAsync(FieldManagementReadAll_Input, null);
        }
        
        /// <remarks/>
        public void FieldManagementReadAllAsync(FieldManagementReadAll_Input FieldManagementReadAll_Input, object userState) {
            if ((this.FieldManagementReadAllOperationCompleted == null)) {
                this.FieldManagementReadAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFieldManagementReadAllOperationCompleted);
            }
            this.InvokeAsync("FieldManagementReadAll", new object[] {
                        FieldManagementReadAll_Input}, this.FieldManagementReadAllOperationCompleted, userState);
        }
        
        private void OnFieldManagementReadAllOperationCompleted(object arg) {
            if ((this.FieldManagementReadAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FieldManagementReadAllCompleted(this, new FieldManagementReadAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementRead", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FieldManagementRead_Output", Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
        public FieldManagementRead_Output FieldManagementRead([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")] FieldManagementRead_Input FieldManagementRead_Input) {
            object[] results = this.Invoke("FieldManagementRead", new object[] {
                        FieldManagementRead_Input});
            return ((FieldManagementRead_Output)(results[0]));
        }
        
        /// <remarks/>
        public void FieldManagementReadAsync(FieldManagementRead_Input FieldManagementRead_Input) {
            this.FieldManagementReadAsync(FieldManagementRead_Input, null);
        }
        
        /// <remarks/>
        public void FieldManagementReadAsync(FieldManagementRead_Input FieldManagementRead_Input, object userState) {
            if ((this.FieldManagementReadOperationCompleted == null)) {
                this.FieldManagementReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFieldManagementReadOperationCompleted);
            }
            this.InvokeAsync("FieldManagementRead", new object[] {
                        FieldManagementRead_Input}, this.FieldManagementReadOperationCompleted, userState);
        }
        
        private void OnFieldManagementReadOperationCompleted(object arg) {
            if ((this.FieldManagementReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FieldManagementReadCompleted(this, new FieldManagementReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementUpsert", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FieldManagementUpsert_Output", Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
        public FieldManagementUpsert_Output FieldManagementUpsert([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")] FieldManagementUpsert_Input FieldManagementUpsert_Input) {
            object[] results = this.Invoke("FieldManagementUpsert", new object[] {
                        FieldManagementUpsert_Input});
            return ((FieldManagementUpsert_Output)(results[0]));
        }
        
        /// <remarks/>
        public void FieldManagementUpsertAsync(FieldManagementUpsert_Input FieldManagementUpsert_Input) {
            this.FieldManagementUpsertAsync(FieldManagementUpsert_Input, null);
        }
        
        /// <remarks/>
        public void FieldManagementUpsertAsync(FieldManagementUpsert_Input FieldManagementUpsert_Input, object userState) {
            if ((this.FieldManagementUpsertOperationCompleted == null)) {
                this.FieldManagementUpsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFieldManagementUpsertOperationCompleted);
            }
            this.InvokeAsync("FieldManagementUpsert", new object[] {
                        FieldManagementUpsert_Input}, this.FieldManagementUpsertOperationCompleted, userState);
        }
        
        private void OnFieldManagementUpsertOperationCompleted(object arg) {
            if ((this.FieldManagementUpsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FieldManagementUpsertCompleted(this, new FieldManagementUpsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/odesabs/FieldManagement/:FieldManagementCreate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FieldManagementCreate_Output", Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
        public FieldManagementCreate_Output FieldManagementCreate([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")] FieldManagementCreate_Input FieldManagementCreate_Input) {
            object[] results = this.Invoke("FieldManagementCreate", new object[] {
                        FieldManagementCreate_Input});
            return ((FieldManagementCreate_Output)(results[0]));
        }
        
        /// <remarks/>
        public void FieldManagementCreateAsync(FieldManagementCreate_Input FieldManagementCreate_Input) {
            this.FieldManagementCreateAsync(FieldManagementCreate_Input, null);
        }
        
        /// <remarks/>
        public void FieldManagementCreateAsync(FieldManagementCreate_Input FieldManagementCreate_Input, object userState) {
            if ((this.FieldManagementCreateOperationCompleted == null)) {
                this.FieldManagementCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFieldManagementCreateOperationCompleted);
            }
            this.InvokeAsync("FieldManagementCreate", new object[] {
                        FieldManagementCreate_Input}, this.FieldManagementCreateOperationCompleted, userState);
        }
        
        private void OnFieldManagementCreateOperationCompleted(object arg) {
            if ((this.FieldManagementCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FieldManagementCreateCompleted(this, new FieldManagementCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementReadAll_Input {
        
        private bool includeAllField;
        
        private bool includeAllFieldSpecified;
        
        /// <remarks/>
        public bool IncludeAll {
            get {
                return this.includeAllField;
            }
            set {
                this.includeAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeAllSpecified {
            get {
                return this.includeAllFieldSpecified;
            }
            set {
                this.includeAllFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementCreate_Output {
        
        private string statusField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class CustomFieldTranslationData {
        
        private string languageCodeField;
        
        private string displayNameField;
        
        private string validationErrorMsgField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class CustomFieldData {
        
        private string objectNameField;
        
        private string displayNameField;
        
        private string customFieldTypeField;
        
        private string integrationTagField;
        
        private string genericIntegrationTagField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string defaultValueField;
        
        private string customFieldValidationField;
        
        private bool postDefaultField;
        
        private bool postDefaultFieldSpecified;
        
        private string validationErrorMsgField;
        
        private CustomFieldTranslationData[] listOfCustomFieldTranslationsField;
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFieldType {
            get {
                return this.customFieldTypeField;
            }
            set {
                this.customFieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationTag {
            get {
                return this.integrationTagField;
            }
            set {
                this.integrationTagField = value;
            }
        }
        
        /// <remarks/>
        public string GenericIntegrationTag {
            get {
                return this.genericIntegrationTagField;
            }
            set {
                this.genericIntegrationTagField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadOnlySpecified {
            get {
                return this.readOnlyFieldSpecified;
            }
            set {
                this.readOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string CustomFieldValidation {
            get {
                return this.customFieldValidationField;
            }
            set {
                this.customFieldValidationField = value;
            }
        }
        
        /// <remarks/>
        public bool PostDefault {
            get {
                return this.postDefaultField;
            }
            set {
                this.postDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostDefaultSpecified {
            get {
                return this.postDefaultFieldSpecified;
            }
            set {
                this.postDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomFieldTranslation", IsNullable=false)]
        public CustomFieldTranslationData[] ListOfCustomFieldTranslations {
            get {
                return this.listOfCustomFieldTranslationsField;
            }
            set {
                this.listOfCustomFieldTranslationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementCreate_Input {
        
        private CustomFieldData customFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
        public CustomFieldData CustomField {
            get {
                return this.customFieldField;
            }
            set {
                this.customFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementUpsert_Output {
        
        private string statusField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementUpsert_Input {
        
        private FieldSetData fieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
        public FieldSetData FieldSet {
            get {
                return this.fieldSetField;
            }
            set {
                this.fieldSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class FieldSetData {
        
        private string objectNameField;
        
        private FieldData[] listOfFieldsField;
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldData[] ListOfFields {
            get {
                return this.listOfFieldsField;
            }
            set {
                this.listOfFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class FieldData {
        
        private string nameField;
        
        private string displayNameField;
        
        private string fieldTypeField;
        
        private string integrationTagField;
        
        private string genericIntegrationTagField;
        
        private bool requiredField;
        
        private bool requiredFieldSpecified;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string defaultValueField;
        
        private string fieldValidationField;
        
        private bool postDefaultField;
        
        private bool postDefaultFieldSpecified;
        
        private string validationErrorMsgField;
        
        private FieldTranslationData[] listOfFieldTranslationsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IntegrationTag {
            get {
                return this.integrationTagField;
            }
            set {
                this.integrationTagField = value;
            }
        }
        
        /// <remarks/>
        public string GenericIntegrationTag {
            get {
                return this.genericIntegrationTagField;
            }
            set {
                this.genericIntegrationTagField = value;
            }
        }
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiredSpecified {
            get {
                return this.requiredFieldSpecified;
            }
            set {
                this.requiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadOnlySpecified {
            get {
                return this.readOnlyFieldSpecified;
            }
            set {
                this.readOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string FieldValidation {
            get {
                return this.fieldValidationField;
            }
            set {
                this.fieldValidationField = value;
            }
        }
        
        /// <remarks/>
        public bool PostDefault {
            get {
                return this.postDefaultField;
            }
            set {
                this.postDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostDefaultSpecified {
            get {
                return this.postDefaultFieldSpecified;
            }
            set {
                this.postDefaultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldTranslation", IsNullable=false)]
        public FieldTranslationData[] ListOfFieldTranslations {
            get {
                return this.listOfFieldTranslationsField;
            }
            set {
                this.listOfFieldTranslationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
    public partial class FieldTranslationData {
        
        private string languageCodeField;
        
        private string displayNameField;
        
        private string validationErrorMsgField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementRead_Output {
        
        private FieldSetData[] listOfFieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldSet", IsNullable=false)]
        public FieldSetData[] ListOfFieldSet {
            get {
                return this.listOfFieldSetField;
            }
            set {
                this.listOfFieldSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class FieldTranslationQuery {
        
        private Empty languageCodeField;
        
        private Empty displayNameField;
        
        private Empty validationErrorMsgField;
        
        /// <remarks/>
        public Empty LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public Empty DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Empty ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class Empty {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class FieldQuery {
        
        private string nameField;
        
        private Empty displayNameField;
        
        private Empty fieldTypeField;
        
        private Empty integrationTagField;
        
        private Empty genericIntegrationTagField;
        
        private Empty requiredField;
        
        private Empty readOnlyField;
        
        private Empty defaultValueField;
        
        private Empty fieldValidationField;
        
        private Empty postDefaultField;
        
        private Empty validationErrorMsgField;
        
        private FieldTranslationQuery[] listOfFieldTranslationsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Empty DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Empty FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public Empty IntegrationTag {
            get {
                return this.integrationTagField;
            }
            set {
                this.integrationTagField = value;
            }
        }
        
        /// <remarks/>
        public Empty GenericIntegrationTag {
            get {
                return this.genericIntegrationTagField;
            }
            set {
                this.genericIntegrationTagField = value;
            }
        }
        
        /// <remarks/>
        public Empty Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        public Empty ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        public Empty DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public Empty FieldValidation {
            get {
                return this.fieldValidationField;
            }
            set {
                this.fieldValidationField = value;
            }
        }
        
        /// <remarks/>
        public Empty PostDefault {
            get {
                return this.postDefaultField;
            }
            set {
                this.postDefaultField = value;
            }
        }
        
        /// <remarks/>
        public Empty ValidationErrorMsg {
            get {
                return this.validationErrorMsgField;
            }
            set {
                this.validationErrorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldTranslation", IsNullable=false)]
        public FieldTranslationQuery[] ListOfFieldTranslations {
            get {
                return this.listOfFieldTranslationsField;
            }
            set {
                this.listOfFieldTranslationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
    public partial class FieldSetQuery {
        
        private string objectNameField;
        
        private bool includeAllField;
        
        private bool includeAllFieldSpecified;
        
        private FieldQuery[] listOfFieldsField;
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeAll {
            get {
                return this.includeAllField;
            }
            set {
                this.includeAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeAllSpecified {
            get {
                return this.includeAllFieldSpecified;
            }
            set {
                this.includeAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldQuery[] ListOfFields {
            get {
                return this.listOfFieldsField;
            }
            set {
                this.listOfFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementRead_Input {
        
        private FieldSetQuery fieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/query")]
        public FieldSetQuery FieldSet {
            get {
                return this.fieldSetField;
            }
            set {
                this.fieldSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:crmondemand/ws/odesabs/fieldmanagement/")]
    public partial class FieldManagementReadAll_Output {
        
        private FieldSetData[] listOfFieldSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:/crmondemand/xml/fieldmanagement/data")]
        [System.Xml.Serialization.XmlArrayItemAttribute("FieldSet", IsNullable=false)]
        public FieldSetData[] ListOfFieldSet {
            get {
                return this.listOfFieldSetField;
            }
            set {
                this.listOfFieldSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FieldManagementReadAllCompletedEventHandler(object sender, FieldManagementReadAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldManagementReadAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FieldManagementReadAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldManagementReadAll_Output Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldManagementReadAll_Output)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FieldManagementReadCompletedEventHandler(object sender, FieldManagementReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldManagementReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FieldManagementReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldManagementRead_Output Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldManagementRead_Output)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FieldManagementUpsertCompletedEventHandler(object sender, FieldManagementUpsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldManagementUpsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FieldManagementUpsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldManagementUpsert_Output Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldManagementUpsert_Output)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void FieldManagementCreateCompletedEventHandler(object sender, FieldManagementCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldManagementCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FieldManagementCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldManagementCreate_Output Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldManagementCreate_Output)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591